### ISSUE TITLE
78a93d4e-044a-4c18-96e1-4efa360216fc

### ISSUE THREAD

**Issue by JzCherry** [HiveGamesOSS/Chunker#100]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Bedrock 1.21.40

### Output World Version

Bedrock 1.21.30

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
Error identifier: 78a93d4e-044a-4c18-96e1-4efa360216fc

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Thanks for sending the world, seems like it's the same issue as https://github.com/HiveGamesOSS/Chunker/issues/99 which will be fixed in the next release.
