### ISSUE TITLE
Chunker UI crashes in Turkey due to incorrect capitalization

### ISSUE THREAD

**Issue by dunsparce9** [HiveGamesOSS/Chunker#101]
### Chunker Version

1.3.0-main-2cdf4aa

### Platform / Operating System

Windows 11

### Issue Description

[main.log](https://github.com/user-attachments/files/17541445/main.log)

See attached log file. The app tries to access `BasicMessageType.DETECT_VERSİON` (notice the capitalized İ) which doesn't exist, and results in a crash.
This can be fixed by ignoring culture/locale during string capitalization (C# has `String.ToUpperInvariant()` to fix this, but I don't know about java).

Error displayed is "The backend process was killed unexpectedly."
Also the standalone CLI works fine; only the UI version will crash.

**Comment by FormallyMyles** [comment]
Thanks :) we'll get this fixed for the next release.
