### ISSUE TITLE
Error Chunker Displayed: Failed to open selected file.

### ISSUE THREAD

**Issue by The-Ragster** [HiveGamesOSS/Chunker#102]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Failed to open selected file.

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

If there's any further details you can provide which might help with the issue or the type of world you're trying to select.

**Comment by FormallyMyles** [comment]
I'll close this issue for now as I didn't hear back from you, if it still happens feel free to provide the world / logs and we can look further :)
