### ISSUE TITLE
Trying to transfer a very large world 

### ISSUE THREAD

**Issue by Brody-dpt** [HiveGamesOSS/Chunker#104]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Java 1.12.2

### Output World Version

Java 1.21.1

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Your system ran out of memory while converting, please try again, use a smaller world or try a different machine.
I have allocated tons of ram and have also cleared much space for the world to download.

**Comment by Brody-dpt** [comment]
I am attempting to transfer the world on a different drive by putting the folder it is converting in the separate drive will get back if it works. fyi the world is around 20gb

**Comment by Brody-dpt** [comment]
still failed

**Comment by FormallyMyles** [comment]
Because of the processing Chunker does and the compression in Minecraft. You usually need at least the size of your world in RAM (can be more depends on the world), unless you prune it or use a tool like MCASelector to reduce the size.
