### ISSUE TITLE
Converting world error

### ISSUE THREAD

**Issue by Salkgamer** [HiveGamesOSS/Chunker#106]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Bedrock 1.21.40

### Output World Version

Bedrock 1.21.40

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by Salkgamer** [comment]
Sure, here i
 qg1t59QdNJA=.zip
<https://drive.google.com/file/d/1DDIIljXSXvBIP0SQs3QUm4YjfAiuns07/view?usp=drive_web>
t is.

Em qua., 30 de out. de 2024 às 06:24, Myles ***@***.***>
escreveu:

**Comment by FormallyMyles** [comment]
Awesome, thank you, seems to be related to two issues in the world:
- It fails to correctly retain world data because of an old/unknown dimension
- There is a chunk with corrupted/old entity data which it fails to convert.

We'll look into getting this fixed for the next release :)

**Comment by FormallyMyles** [comment]
This should be fixed in the latest release - https://github.com/HiveGamesOSS/Chunker/releases :)
