### ISSUE TITLE
Error while trying to convert world

### ISSUE THREAD

**Issue by PeawGitHub** [HiveGamesOSS/Chunker#107]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

1.21.41

### Output World Version

Any

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: Oops, failed to connect to backend - The backend process was killed unexpectedly.

It happens when I try to upload any Bedrock world folder, I'm attaching an example world if needed:
[world.zip](https://github.com/user-attachments/files/17607099/world.zip)

This is the log:
[main.log](https://github.com/user-attachments/files/17607100/main.log)

**Comment by FormallyMyles** [comment]
Seems like the same issue as https://github.com/HiveGamesOSS/Chunker/issues/101, we'll have this fixed in the next release :)
