### ISSUE TITLE
Won't open world

### ISSUE THREAD

**Issue by Timothy407168** [HiveGamesOSS/Chunker#113]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: Unable to run chunker-cli backend.

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- Have you tried redownloading the application?

**Comment by Timothy407168** [comment]
Like 15 more tries after reporting the issue with the same result, I restarted my computer. It started to work but, now it keeps exporting the world with lots of missing chunks.

**Comment by Timothy407168** [comment]
> Like 15 more tries after reporting the issue with the same result, I restarted my computer. It started to work but, now it keeps exporting the world with lots of missing chunks.

No, I did not reinstall the application because my computer was warning me how that the application I installed " might contain malware."

**Comment by FormallyMyles** [comment]
If you're able to look for the log file as written above, we can look further and if you're able to show screenshots for any malware warnings we can also look into that. We do digitally sign the windows version so it shouldn't happen.

**Comment by Timothy407168** [comment]
Here is the logs. I had a hard time finding them because my computer stores files differently than most people say it does.
[Chunker Logs.docx](https://github.com/user-attachments/files/17725126/Chunker.Logs.docx)
My subscription with my antivirus ended and it wont let me see the logs and scans.

**Comment by FormallyMyles** [comment]
I had a look through your log and this is generally my conclusion:
- Sometimes if you open Chunker twice before it's fully loaded or if something like an anti-virus prevents it loading all the files you can see an error where it states `Unable to run chunker-cli backend.` or similar, it looks like that may have happened a few times.
- I can see you managed to convert a world; I assume you downgraded the version (e.g. 1.21 -> 1.20) as there's a few vault blocks removed.

I know you mentioned in another issue about chunks being missing, as a note, if you're converting from Bedrock the world only contains chunks which have been changed (e.g. blocks placed), so you might be running into that.

What antivirus were you using so we can look into it further?

**Comment by Timothy407168** [comment]
I have been using McAfee, but I can't find the logs.

**Comment by FormallyMyles** [comment]
Given that VirusTotal isn't flagging anything, I would think it's an odd false positive - https://www.virustotal.com/gui/file/a2747f11cace5c697b16ac183a0be889ac34bcbd13b1729d64b731ec97331679. I'll close this issue for now as I don't think there's anything we can fix and I assume McAfee would of fixed the false warning.

If you have any issues with things disappearing do not hesitate to open an issue with logs / screenshots and we can look further :)
