### ISSUE TITLE
stone_slab and chest loot tables

### ISSUE THREAD

**Issue by Ma3-a** [HiveGamesOSS/Chunker#116]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Java 1.13.2

### Output World Version

Java 1.20.2

### Platform / Operating System

Windows 10

### Issue Description

When comparing outputs of the web and oss versions of chunker I found 2 parity issues in a village.
This was done when converting a java 1.13.2 world to java 1.20.2.

## stone_slab[type="bottom"]

The web version converts to smooth_stone slab, the oss version converts to stone_slab. For reference, loading it in a 1.20.2 client converts these blocks to smooth_stone_slab.

## chest loot table "minecraft:chests/village_blacksmith"

The web version converts? to "minecraft:chests/village_blacksmith", the oss version deletes the loot table. For reference, loading it in a 1.20.2 client converts this loot table to "minecraft:chests/village/village_weaponsmith".

**Comment by FormallyMyles** [comment]
Thanks for reporting these, we'll have them fixed for the next release :)

**Comment by FormallyMyles** [comment]
This should be fixed in the latest release - https://github.com/HiveGamesOSS/Chunker/releases :)
