### ISSUE TITLE
World Convert Issue 

### ISSUE THREAD

**Issue by Popkid2007XD** [HiveGamesOSS/Chunker#120]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Bedrock 1.21.40

### Output World Version

Java 1.21.3

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.
