### ISSUE TITLE
Chunker Offline

### ISSUE THREAD

**Issue by Timothy407168** [HiveGamesOSS/Chunker#121]
### What feature would you like seen in Chunker?

Can you guys make Chunker work offline. My internet is really bad, so any time I want to use the internet I would have to go to the library. I noticed that Chunker won't open the world unless it online conected to a server somewhere. In other words I can't do my work on the go or at home.

**Comment by FormallyMyles** [comment]
Chunker doesn't/shouldn't use the internet apart from when you initially download it from GitHub. I've done two basic tests to ensure this is still the case:
- Disabled my internet via Network Connections and verified I could open Chunker and convert a world
- Created a Windows 10 Virtual Machine that doesn't have internet and copied Chunker to it via USB and verified I could convert a world.

If you're able to provide more details on the OS that this happens on / logs from `%APPDATA%/chunker-electron/logs` we can look further.
