### ISSUE TITLE
NPCs are deleted

### ISSUE THREAD

**Issue by OmniacDev** [HiveGamesOSS/Chunker#122]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Bedrock 1.21.40

### Output World Version

Bedrock 1.21.40

### Platform / Operating System

Windows 11

### Issue Description

After changing my world's generator to void and converting it (to the same version), all the NPCs have been deleted.

**Comment by FormallyMyles** [comment]
Thanks for reporting this, we'll look into getting this fixed for the next release :)

**Comment by FormallyMyles** [comment]
This should be fixed in the latest release - https://github.com/HiveGamesOSS/Chunker/releases :)
