### ISSUE TITLE
Chunker-1.3.1-windows-x86 doesn't launch

### ISSUE THREAD

**Issue by Lucien0214** [HiveGamesOSS/Chunker#123]
### Chunker Version

1.3.1-main-b157b5c

### Platform / Operating System

Windows 8.1

### Description
I attempted to run chunker on my computer, but it failed to launch.

### I tried......
 - Ran chunker with administrative privileges.
 - Relocated chunker to a different directory.
 - Tested an alternative version of chunker. 

__...However, none of these actions work.__

### Additional Information
 - Operating System: Windows 8.1
 - Chunker Version: 1.3.1
 - Java Development Kit: jdk-21
 - Gradle 8.10.2

### Observed Behavior
Upon attempting to launch chunker, it initially consumes system memory and disk resources. After a period, it terminates without any output or error message.

**Comment by FormallyMyles** [comment]
This might be related to you using Windows 8, we've internally only tested on Windows 10 and above. If the folder exists:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)

**Comment by Lucien0214** [comment]
I'm so sorry,but there is no folder `chunker-electron` under `%APPDATA%`.

**Comment by FormallyMyles** [comment]
I've taken a further look and it seems like unfortunately `electron` dropped windows 8 support earlier this year so it's likely related to that. It is still possible to use Chunker but you'd have to use the command line version documented in the README, or use a PC with Windows 10 / Linux.
