### ISSUE TITLE
Failed to convert

### ISSUE THREAD

**Issue by vaxvaa** [HiveGamesOSS/Chunker#124]
### Chunker Version

1.3.1-main-b157b5c

### Input World Version

Bedrock 1.21.40

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion. Error identifier: 56dc3842-32dd-41db-934a-7c9288d23ef5.
it is world that I bought from marketplace in bedrock.

**Comment by FormallyMyles** [comment]
Unfortunately if it's a world you bought from the marketplace it is not possible to convert as they are encrypted.
