### ISSUE TITLE
Unable to run chunker-cli backend

### ISSUE THREAD

**Issue by Snow-hare1** [HiveGamesOSS/Chunker#131]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `Unable to run chunker-cli backend.`

**Comment by FormallyMyles** [comment]
Have you tried closing the app and reopening it? Sometimes this error can happen when you open it twice. Otherwise, you could try the .zip version instead of the .exe to see if that resolves the issue.
