### ISSUE TITLE
맵용량 문제로 변환이 안됨 해결 부탁합니다 

### ISSUE THREAD

**Issue by entu1470** [HiveGamesOSS/Chunker#142]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Java 1.18.0

### Output World Version

Bedrock 1.21.40

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `Your system ran out of memory while converting, please try again, use a smaller world or try a different machine.`

**Comment by FormallyMyles** [comment]
May be related to https://github.com/HiveGamesOSS/Chunker/issues/125, depends on the amount of RAM you have / world size. You may want to try using the cli, a different computer or a smaller map.
