### ISSUE TITLE
Your system ran out of memory during conversion (although there is enough memory)

### ISSUE THREAD

**Issue by DimaVasLazyrit** [HiveGamesOSS/Chunker#144]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Java 1.19.3

### Output World Version

Bedrock 1.21.0

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `Your system ran out of memory while converting, please try again, use a smaller world or try a different machine.`

I don’t understand, I have enough memory. Maybe it's the size of the world? I have it 7 GB. Help please

**Comment by bytewired9** [comment]
are you allocating 7GB to the program or your PC has 7GB?

**Comment by DimaVasLazyrit** [comment]
I didn't say it quite right. My 7 GB weighs the world. Both memory disks have a couple of times more than this number. RAM 16 GB. After looking at other solutions, I still don’t understand what needs to be changed in the settings or somewhere else

**Comment by FormallyMyles** [comment]
Seems related to https://github.com/HiveGamesOSS/Chunker/issues/125, depends on the amount of RAM you have / world size. You may want to try using the cli, a different computer or a smaller map. We'll be hopefully improving this in the next release.
