### ISSUE TITLE
Custom Superflat settings not transferred from bedrock

### ISSUE THREAD

**Issue by bytewired9** [HiveGamesOSS/Chunker#145]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

Bedrock 1.21.40

### Output World Version

Java 1.21.3

### Platform / Operating System

Windows 11

### Issue Description

My bedrock world has custom superflat layers, and those layers are not being transferred to java edition, and just set to the defaults.
![image](https://github.com/user-attachments/assets/5d3c871a-35fc-4f33-b952-29738f68c41b)

**Comment by FormallyMyles** [comment]
This currently isn't a feature of Chunker, the generation features change quite a bit over the history of Java / Bedrock and doesn't quite match in parity making it more complicated to implement, it's a consideration for the future but currently isn't planned.

**As a workaround: **
You can either make a new world with the layers you want and the same settings and copy over the level.dat or use an NBT editor like NBTExplorer to copy the "WorldGenSettings" tag.
