### ISSUE TITLE
Build Failed: Process 'command 'git'' finished with non-zero exit value 128	

### ISSUE THREAD

**Issue by InternetNinjo** [HiveGamesOSS/Chunker#146]
### Chunker Version

1.4.0

### Platform / Operating System

Windows 10

### Issue Description

This is the build scan it generated as per --scan parameter

https://scans.gradle.com/s/xwtx5pglpi62i

I don't fully understand how build things work but i wanted to try to built it myself

**Comment by FormallyMyles** [comment]
Would you mind answering the following:
- Do you currently have git setup on your machine / did you clone the repo using `git clone git://github.com/HiveGamesOSS/Chunker.git`?
- What build command did you run?

From guessing, the cause is it's trying to pull the git info but doesn't have it because it wasn't cloned.

**Comment by InternetNinjo** [comment]
> Would you mind answering the following:
> 
>     * Do you currently have git setup on your machine / did you clone the repo using `git clone git://github.com/HiveGamesOSS/Chunker.git`?
> 
>     * What build command did you run?
> 
> 
> From guessing, the cause is it's trying to pull the git info but doesn't have it because it wasn't cloned.

Sorry about the late response,

1) i've tried via both downloading as zip and the git clone command, and yes i have git setup.
2) ./gradlew build

Unsure why git failed with non-zero exit value 128

**Comment by FormallyMyles** [comment]
If you run the following command while in the directory `git describe --tags --always` what does it output?

**Comment by InternetNinjo** [comment]
> git describe --tags --always

1.4.0

**Comment by FormallyMyles** [comment]
If you're able to, would you mind opening this file locally https://github.com/HiveGamesOSS/Chunker/blob/86becbf5a59a9a527a009e376dbc69e6d2fe3136/cli/build.gradle.kts#L110
(cli/build.gradle.kts)

and testing Line 110 with the following:
`commandLine("cmd", "git", "branch", "--show-current")`

and Line 116 with the following:
`commandLine("cmd", "git", "describe", "--tags", "--always")`

Then trying to build it again via `./gradlew build`, this is based on this stackoverflow answer https://stackoverflow.com/a/51644353 which seems to suggest adding "cmd" might fix it for some windows versions :)

**Comment by InternetNinjo** [comment]
> If you're able to, would you mind opening this file locally
> 
> https://github.com/HiveGamesOSS/Chunker/blob/86becbf5a59a9a527a009e376dbc69e6d2fe3136/cli/build.gradle.kts#L110
> 
> (cli/build.gradle.kts)
> 
> and testing Line 110 with the following: `commandLine("cmd", "git", "branch", "--show-current")`
> 
> and Line 116 with the following: `commandLine("cmd", "git", "describe", "--tags", "--always")`
> 
> Then trying to build it again via `./gradlew build`, this is based on this stackoverflow answer https://stackoverflow.com/a/51644353 which seems to suggest adding "cmd" might fix it for some windows versions :)

the gradle file only has 72 lines smh, cmd seems to be working but slow

**Comment by InternetNinjo** [comment]
> commandLine("cmd", "git", "describe", "--tags", "--always")

going to try those lines, cmd seems to be working too but slower than powershell preview 7

**Comment by FormallyMyles** [comment]
The project uses Java 17 when building for consistency, you can optionally change https://github.com/HiveGamesOSS/Chunker/blob/main/cli/build.gradle.kts#L46 to your Java version.

**Comment by InternetNinjo** [comment]
> The project uses Java 17 when building for consistency, you can optionally change https://github.com/HiveGamesOSS/Chunker/blob/main/cli/build.gradle.kts#L46 to your Java version.

tbh i got installed all three versions of graalvm jdk, 17, 21, 22
i'll try

**Comment by InternetNinjo** [comment]
> The project uses Java 17 when building for consistency, you can optionally change https://github.com/HiveGamesOSS/Chunker/blob/main/cli/build.gradle.kts#L46 to your Java version.

well i don't think i can build it anyway, thanks for the support, closing
