### ISSUE TITLE
emerlad secret map

### ISSUE THREAD

**Issue by Hybridnate388** [HiveGamesOSS/Chunker#149]
### Chunker Version

1.4.0-main-86becbf

### Input World Version

bedrock 1.21.6 to java 1.12.2

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `Unable to run chunker-cli backend.`
[levelname.txt](https://github.com/user-attachments/files/17898175/levelname.txt)

**Comment by FormallyMyles** [comment]
Have you tried closing the application and running it again? This can happen if you run the application twice before it's fully loaded. Otherwise, If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)

**Comment by Hybridnate388** [comment]
Yes I’ve tried that multiple times and nothing works on changes

**Comment by FormallyMyles** [comment]
Seems odd, ensure you're only opening it once (it can take a while to extract all the data) while it opens. You can also try the .zip version (note: it isn't currently signed like the exe so Windows may have a SmartScreen warning) - [1.4.0 Chunker-1.4.0-windows-x86.zip (download)](https://github.com/HiveGamesOSS/Chunker/releases/download/1.4.0/Chunker-1.4.0-windows-x86.zip)

**Comment by Hybridnate388** [comment]
ae517597-ba85-4d8b-b801-41d8af710a26 so these are the output ids for all
the errors with getting the world i want converted that it gave me before
finishing the process

**Comment by FormallyMyles** [comment]
The error you get is due to an invalid entity in the world (maybe due to corruption or if the world is really old), this can be ignored.

**Comment by Hybridnate388** [comment]
yea because the world is kinda old because its suppose to be for 1.12.2 and
you can get that in bedrock like you in java
