### ISSUE TITLE
Failed to connect to backend

### ISSUE THREAD

**Issue by luigi052005** [HiveGamesOSS/Chunker#163]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

Java .1.20.6

### Output World Version

Java .1.20.4

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `The backend process was killed unexpectedly.`

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.
