### ISSUE TITLE
does anyone know how to solve this issue???

### ISSUE THREAD

**Issue by mrsamio** [HiveGamesOSS/Chunker#175]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Displayed: `Failed to open selected folder, please ensure you don't have it open anywhere else.`

**Comment by FormallyMyles** [comment]
That error happens when Chunker is unable to open the folder because something else has it open. Ensure you're closing Minecraft and other tools before opening your world in Chunker.
