### ISSUE TITLE
big world 20gb

### ISSUE THREAD

**Issue by BitCoinOffical** [HiveGamesOSS/Chunker#18]
### What feature would you like seen in Chunker?

I am writing about chanker.app. I have a Java World of 20GB and since it is too big I can't port it to Minecraft BE/PE. Please fix(((

**Comment by FormallyMyles** [comment]
This issue tracker here relates to the downloadable version (with a similar GUI to the website) - https://github.com/HiveGamesOSS/Chunker/releases/

It is technically possible to convert a 20GB world with the new version though the bigger the world the more resources you'll need to efficiently convert it. I would highly suggest using a tool like MCASelector to cut down your world before conversion.
