### ISSUE TITLE
Oops, Failed to save

### ISSUE THREAD

**Issue by Davidschgl** [HiveGamesOSS/Chunker#181]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

Java .1.21.1

### Output World Version

Bedrock .R21.40

### Platform / Operating System

win64

### Issue Description

Error Displayed when I want to save the convertet world: `Oops Failed to save.`

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.
