### ISSUE TITLE
The backend process was killed unexpectedly

### ISSUE THREAD

**Issue by loeasy68** [HiveGamesOSS/Chunker#185]
### Chunker Version

1.4.2-main-daee346

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

linux-x64-6.8.0-49-generic

### Issue Description

Error Displayed: `The backend process was killed unexpectedly.`

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `~/.config/chunker-electron/logs/main.log`, or the terminal if you're running chunker from it.
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Closing this as I didn't hear back from you, if it's still occurring please send us the log as we'd love to fix this if it's an issue :)
