### ISSUE TITLE
All apps are closed, and the world selected has no copies

### ISSUE THREAD

**Issue by thereallego** [HiveGamesOSS/Chunker#186]
### Chunker Version

1.4.1-main-6cce3ef

### Input World Version

bedrock 1.21.51

### Output World Version

bedrock 1.21.51

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `Failed to open selected file, please ensure you don't have it open anywhere else.`

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Closing as we haven't heard back from you, if it's still an issue and you can provide the logs / world, let us know :)
