### ISSUE TITLE
Transfer player data for the same name

### ISSUE THREAD

**Issue by PeawGitHub** [HiveGamesOSS/Chunker#2]
### What feature would you like seen in Chunker?

I think player data can be transfered for players that use the same name in both versions. i.e. Someone with the name "Moobloom" in Java Edition will have the same player data (inventory, etc.) in Bedrock version of the world because their Xbox name is "Moobloom" as well.

**Comment by FormallyMyles** [comment]
The new open-source Chunker does transfer player data for the local player. 

In regards to multiplayer worlds, it becomes complicated as we'd need to link up the XUID / UUID and match usernames which isn't currently planned due to the work needed.

**Comment by PeawGitHub** [comment]
Alright, thank you.
