### ISSUE TITLE
Error when converting "Valentines Dropper - 2024 Edition! (Map for Minecraft Bedrock)"

### ISSUE THREAD

**Issue by Newbytee** [HiveGamesOSS/Chunker#205]
### Chunker Version

1.4.3-main-60b484e

### Input World Version

Bedrock 1.20.60

### Output World Version

1.21.3

### Platform / Operating System

Fedora 40 (AppImage)

### Issue Description

After converting "Valentines Dropper - 2024 Edition! (Map for Minecraft Bedrock)" from Bedrock to Java as described above, I get errors:

Map: https://www.planetminecraft.com/project/valentines-dropper-2024-edition-map-for-minecraft-bedrock/
Support ID: 50827ced-1d9e-421b-850e-607a36f07a25
Log: [main.log](https://github.com/user-attachments/files/18199010/main.log)

I haven't tested the map to see if it works well anyway yet.

**Comment by FormallyMyles** [comment]
Based on the error it means that the map contains chunks older than Chunker supports. You might find the world is fine, as in some cases it's empty chunks or chunks far away from the map. If you have access to Bedrock, the world can be upgraded by placing/breaking a block in the faulty chunks.

**Comment by FormallyMyles** [comment]
Unfortunately it's not within scope (and i'm not sure we have the data to recover some of the data), you might find the world works fine, as that sometimes is the case with maps that aren't fully upgraded.
