### ISSUE TITLE
юд

### ISSUE THREAD

**Issue by Hacker979** [HiveGamesOSS/Chunker#207]
### Chunker Version

1.4.3-main-60b484e

### Input World Version

N/A

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Displayed: `Failed to open selected folder, please ensure you don't have it open anywhere else.`

**Comment by FormallyMyles** [comment]
Ensure you've closed Minecraft as Chunker is unable to open the world if it's in use.
