### ISSUE TITLE
Error while convert chunks with exclusive MCBE blocks.

### ISSUE THREAD

**Issue by Max-RM** [HiveGamesOSS/Chunker#21]
### Chunker Version

any version

### Platform / Operating System

Any OS

### Issue Description

It seems that if the MCBE worlds contain blocks such as Glowingobsidian, netherreactor, MCEE chimestry blocks, infoupdate, etc... then chunks with these blocks will be completely deleted when convert world to the MCJE.

Here Error log: https://github.com/user-attachments/files/16741383/Chunker2log.txt

And here video where you can see that some chunks want converted: https://youtu.be/CF8vaN3kd6c
timecode: 3:48

If its needed I can send my world but only in dm.

**solution**:
Add code to the Chunker that will ignore the exclusive MCBE blocks so the chunk will be converted, but the exclusive MCBE blocks will be turned into air. At least it's better than not having the chunk at all.

**Comment by Max-RM** [comment]
> Chunker should just be able to convert those chunks and ignore the blocks

Maybe this doesn't work for some world versions? In my case 1.16.40.02 MCBE to 1.16.4 MCJE.

World also was sender.

**Comment by FormallyMyles** [comment]
So for your world, you'll find full logs in the console where you ran the application (in Linux). In these logs (and after running the world on my PC) it'll report `Unsupported chunk version 1` which basically means the world has chunks which are just too old for Chunker to understand (version 1 was used roughly before 1.5.0 MCBE).

You can get the game to upgrade these chunks, you just need to place a block in the chunk and destroy it which unfortunately is a bit tedious.

**Comment by Max-RM** [comment]
> world has chunks which are just too old for Chunker to understand

Hi. Can you open issue back? I tried to convert my world from MCBE 1.21 to Java 1.21 and got absolutely same error:
![image](https://github.com/user-attachments/assets/be1ccd34-8535-4885-aa02-934167856139)

And this world has always been on version 1.21 and does not contain chunks from older versions.

**Comment by FormallyMyles** [comment]
Could you check with the latest release (1.1.2)? And otherwise provide the main.log from the conversion that yields it?

**Comment by Max-RM** [comment]
> Could you check with the latest release (1.1.2)? And otherwise provide the main.log from the conversion that yields it?

Ok

**Comment by Max-RM** [comment]
> Could you check with the latest release (1.1.2)? And otherwise provide the main.log from the conversion that yields it?

Done!

Many thanks for this fix. Now it works correctly. I will compile new version for Arch linux ARM64
