### ISSUE TITLE
Unable to run chunker-cli backend MacOS

### ISSUE THREAD

**Issue by DanielCGL** [HiveGamesOSS/Chunker#28]
### Chunker Version

1.1.0-main-3de8fa0

### Input World Version

1.19 Bedrock

### Output World Version

1.16.5 Java

### Platform / Operating System

darwin-arm64-22.6.0

### Issue Description

Error Chunker Displayed: Unable to run chunker-cli backend.

**Comment by DanielCGL** [comment]
[main.log](https://github.com/user-attachments/files/16902981/main.log)

I've re-installed, quit, re-open the app, nothing has changed, installed by the dmg file.

**Comment by FormallyMyles** [comment]
Thanks for providing this, seems like our path logic isn't quite right, we'll look into getting this fixed for the next release

**Comment by FormallyMyles** [comment]
This should be fixed in our latest release - https://github.com/HiveGamesOSS/Chunker/releases/
