### ISSUE TITLE
Provide a Dockerfile and host it inside the github registry

### ISSUE THREAD

**Issue by KCodeYT** [HiveGamesOSS/Chunker#3]
### What feature would you like seen in Chunker?

It would be nice to have container images for the Chunker CLI and Web Application. These could be hosted in the github registry, ensuring that not everybody needs to build the images on their own.

Edit: As I just saw it now, that the web application has been marked as legacy and has been replaced by the Java Application, but it would still be great to have the ability to run the Chunker CLI inside containers for automated world conversion.
However the wider user base would not profit of that, as not many need a service to convert java edition worlds automatically to bedrock edition.

**Comment by zelytra** [comment]
Docker don't work like this. You can expose ports from the docker for external usage. Using Docker to exposing CLI is not possible. 
As you said first, if it was a web service theire will be no problem to do this but as the app is now all in java runnable app you cannot longer do this.
