### ISSUE TITLE
Minecraft does not reconnize my converted map+Conversion issue

### ISSUE THREAD

**Issue by DanielCGL** [HiveGamesOSS/Chunker#32]
### Chunker Version

1.1.1-main-79e9191

### Input World Version

Bedrock 1.21.20

### Output World Version

Java 1.16.5

### Platform / Operating System

MacOS

### Issue Description

Minecraft does not recongize the my converted map by using the App on MacOS, but when using the web version to convert my map, Minecraft will recognize my converted map.

I believe it's a level.dat conversion problem, because when I change a new level.dat, Minecraft will start to recognize my map. I've upload my main.log and main.old.log, as well as my level.dat and output log after conversion.

[main.log](https://github.com/user-attachments/files/16918834/main.log)

[main.old.log](https://github.com/user-attachments/files/16918837/main.old.log)

[level.dat.zip](https://github.com/user-attachments/files/16918842/level.dat.zip)

[output_log.txt](https://github.com/user-attachments/files/16918857/output_log.txt)

**Comment by FormallyMyles** [comment]
The level.dat you provided is definitely corrupted, have you retried converting / is there a chance you copied the file before the download was complete? Does the issue happen with other worlds you've tried?

I did a similar test on MacOS with a 1.21.0 Bedrock world to Java 1.16.5 and the only thing I could find was bottom of the world being cut-off which is expected as 1.16.5 does not have the same height.

The errors in your conversion log (`Unsupported chunk version 0`) relate to the Bedrock world having really old chunks (older than 1.8 MCBE) and Chunker doesn't know how to load these, you can explore the world on Bedrock and add blocks to these chunks and the engine will upgrade them.

**Comment by DanielCGL** [comment]
I have retried converting my map on MacOS but it generate the corrupted level.dat. But the thing is I've tried converting one of my other maps and it seems to working well. It might be due to my corrupted file map is quite big(Bedrock version is about 300MB), where as the map that converted successful is quite small (Bedrock version is about 60MB), would you have any chance to trying to convert a big size map?

I understand that you mentioned the error, and that's in my expectation, and I also believe that the corrupted level.dat file problem has no relation with that error.

**Comment by FormallyMyles** [comment]
> I have retried converting my map on MacOS but it generate the corrupted level.dat as usual. But the thing is I've tried converting one of my other maps and it seems to working well. It might be due to my corrupted file map is quite big(Bedrock version is about 300MB), where as the map that converted successful is quite small (Bedrock version is about 60MB), would you have any chance to trying to convert a big size map?
> 
> I understand that you mentioned the error, and that's in my expectation, and I also believe that the corrupted level.dat file problem has no relation with that error.

Definitely seems odd, if you want to email the map to `chunker-public@hivemc.com` we can take a further look and see if we can replicate it. I've not tried huge maps on Mac but Chunker definitely works fine for multi-gigabyte maps at least for Windows / Linux.

**Comment by FormallyMyles** [comment]
I've taken a look at the issue and it seems Chunker has some code wrong when it reads UTF characters in NBT because it's transferring your player data one of the items seems to trip it up when writing.

We should have this fixed for the next patch release. I'll close the issue and let you know when that happens. 

If you wanted to look at your map in the mean time, logging into Bedrock and clearing your inventory would be the temporary solution.

**Comment by DanielCGL** [comment]
Thanks, clear the inventory does work, now Java does recognize my map, but it seems like when converting map, some chunks in bedrock Minecraft are disappeared after converting to Java. I've attached the pictures for comparison.
Converted Java Version:
<img width="1239" alt="Converted Java Version" src="https://github.com/user-attachments/assets/7e4ef0c5-fda8-4d32-92e4-00fbe74bede9">

Original Bedrock Version:
<img width="567" alt="Original Bedrock version" src="https://github.com/user-attachments/assets/0bba3258-2620-4fa8-b6ae-21042d3c3942">

If necessary, please let me know if you need the coordinates of that section in the map.

**Comment by FormallyMyles** [comment]
The missing chunks you're seeing would be related to one of my previous messages:

> The errors in your conversion log (Unsupported chunk version 0) relate to the Bedrock world having really old chunks (older than 1.8 MCBE) and Chunker doesn't know how to load these, you can explore the world on Bedrock and add blocks to these chunks and the engine will upgrade them.

**Comment by DanielCGL** [comment]
But on the web version everything converts fine, why web conversion is quite different than the actual App?

**Comment by FormallyMyles** [comment]
> But on the web version everything converts fine, why web conversion is quite different than the actual App?

I would guess it's likely down to the item bug which will be fixed in the next patch release, do you know if those chunks contain renamed items etc?

**Comment by KadTheHunter** [comment]
I had issues similar to those posted here, using the web version fixes the issue with certain chunks getting wiped. 

Now though there's a strange bug, where stone brick walls seemingly aren't ported, and there's banners + dropped item frames in weird spots (see pics for reference, first is Bedrock, second is Java)
![image](https://github.com/user-attachments/assets/bb351326-ec9f-4116-809c-d3c794883ea2)
![image](https://github.com/user-attachments/assets/378334bf-5110-42e5-acb4-3a91197f83bf)

I'm sure the banners come from *somewhere*, but I haven't found where they are on Bedrock.

The Bedrock world folder is attached below.

[world.zip](https://github.com/user-attachments/files/16972921/world.zip)

Additionally, barriers aren't being converted, and I saw errors in the Java logs mentioning "invisible_bedrock", which I suspect is what was supposed to be barriers.


Additional images of the weird banner placement:
![image](https://github.com/user-attachments/assets/97021b12-fbf0-49e7-95ea-9c3a6137d4e8)

![image](https://github.com/user-attachments/assets/ba2c6fa6-f414-4930-9ac7-051802bac90d)


Once again, unable to identify where they came from.



Coordinates of this build are around X: 10000 Y: 64 Z: 100

Am willing to do any testing needed, let me know if you need more information.

**Comment by FormallyMyles** [comment]
> I had issues similar to those posted here, using the web version fixes the issue with certain chunks getting wiped.
> 
> Now though there's a strange bug, where stone brick walls seemingly aren't ported, and there's banners + dropped item frames in weird spots (see pics for reference, first is Bedrock, second is Java) ![image](https://private-user-images.githubusercontent.com/47439649/366708923-bb351326-ec9f-4116-809c-d3c794883ea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjI1MDIsIm5iZiI6MTcyNjEyMjIwMiwicGF0aCI6Ii80NzQzOTY0OS8zNjY3MDg5MjMtYmIzNTEzMjYtZWM5Zi00MTE2LTgwOWMtZDNjNzk0ODgzZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjYyODNhM2FmNGVlZjYzNmQxYjVjYTAyNmJhMzhkNjE2NDI0Y2Q4MjhjMjBmYmFkMGQ3NzZmMzJmMjZkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q3QlWh1XbdFb9128RZf3Pmfxorp0qUeSQFD5CAJPiT0) ![image](https://private-user-images.githubusercontent.com/47439649/366709056-378334bf-5110-42e5-acb4-3a91197f83bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjI1MDIsIm5iZiI6MTcyNjEyMjIwMiwicGF0aCI6Ii80NzQzOTY0OS8zNjY3MDkwNTYtMzc4MzM0YmYtNTExMC00MmU1LWFjYjQtM2E5MTE5N2Y4M2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOWJlNWFkMzlkMTUyZjhjZjYxNmUyNTFiMWUxY2Q0M2Q0OWJjZmYwMjM5ZjhjNmIzN2I5OGIyZTliNTY0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhIyGFzO7WdKqwtFMDhUxdyakF32aG8QlNEq7uya_TY)
> 
> I'm sure the banners come from _somewhere_, but I haven't found where they are on Bedrock.
> 
> The Bedrock world folder is attached below.
> 
> [world.zip](https://github.com/user-attachments/files/16972921/world.zip)
> 
> Additionally, barriers aren't being converted, and I saw errors in the Java logs mentioning "invisible_bedrock", which I suspect is what was supposed to be barriers.
> 
> Additional images of the weird banner placement: ![image](https://private-user-images.githubusercontent.com/47439649/366710275-97021b12-fbf0-49e7-95ea-9c3a6137d4e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjI1MDIsIm5iZiI6MTcyNjEyMjIwMiwicGF0aCI6Ii80NzQzOTY0OS8zNjY3MTAyNzUtOTcwMjFiMTItZmJmMC00OWU3LTk1ZWEtOWMzYTYxMzdkNGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMjMwZWZiYjg2OTAwNGMzM2ZlZmJiZThmOWNjNGIxMjE5OGYyMjAzODFjYzk0NzZmYjMzN2M1NDQxOGUxNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pf6btVcJzaRquAI5TeaNh2BFbDuPmEnmOQIUFezlUYs)
> 
> ![image](https://private-user-images.githubusercontent.com/47439649/366710213-ba2c6fa6-f414-4930-9ac7-051802bac90d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjI1MDIsIm5iZiI6MTcyNjEyMjIwMiwicGF0aCI6Ii80NzQzOTY0OS8zNjY3MTAyMTMtYmEyYzZmYTYtZjQxNC00OTMwLTlhYzctMDUxODAyYmFjOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTM1NmE1MmRlYjk2MjZmYWZkYjZhNTdhOGY2ZDEwZWUwMTFhMzVhNDY5NDM3ODQ2OGViMWY3MzVjMTg0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cuViMVQqIpiNdl2l3haxhnajT3b9AXUZJG-okUS9KA)
> 
> Once again, unable to identify where they came from.
> 
> Coordinates of this build are around X: 10000 Y: 64 Z: 100
> 
> Am willing to do any testing needed, let me know if you need more information.
> 
> EDIT: Additionally, it seems plants in flower pots didn't port either.

Please create a new issue for any other issues that aren't related to chunks going missing. Note: we can't directly track issues that regard the website version here though do let us know if you have any of the issues on the downloadable one.

**Comment by DanielCGL** [comment]
After check, I don't think any of the items on my map contains renamed items, but I think I shall wait for the upcoming update and see what's happening from there.

**Comment by DanielCGL** [comment]
It seems like the newest version of Chunker does not have that problem now, thanks!
