### ISSUE TITLE
Hollow oceans

### ISSUE THREAD

**Issue by dadodasyra** [HiveGamesOSS/Chunker#36]
### Chunker Version

cli-1.1.1

### Input World Version

1.20.1 "Modded" Java (see more details in description)

### Output World Version

Bedrock 1.20.0

### Platform / Operating System

Linux Debian 11

### Issue Description

I generated a whole 15k (radius) map on Java 1.20.1 based on neoforge using some custom generation mods (Mod list: Chunky, Flat bedrock, journeymap(should be only client), tectonic, terralith).
Tectonic & Terralith are mods that can generate beautiful maps but using only vanilla content.

After generation I figured out I only needed 10k of radius so I decided to shrink it while converting to bedrock using chunker.
Here's the used command:
`java -Xmx16G -Xms1G -jar chunker-cli-*.jar -i inputs/$1 -o outputs/$2 -f BEDROCK_1_20_0 -m block_mappings.chunker.json -p pruning.chunker.json`
Files:
[block_mappings.chunker.json](https://github.com/user-attachments/files/16949717/block_mappings.chunker.json)
[pruning.chunker.json](https://github.com/user-attachments/files/16949718/pruning.chunker.json)

After this I checked if everything was fine using a Pocketmine server (that does not converted the map at any time nor altered its content) and saw this : 
![image](https://github.com/user-attachments/assets/8328bcd8-a15b-4a9b-89d7-40ab17cba885)
For comparison on the java map : 
![image](https://github.com/user-attachments/assets/eb526702-d133-42b8-9c59-fe283ec3cf47)

It seems that subchunks that were only filled with water were just removed from the map (first separation at y16; second one at y32 etc..) The one with kelp stayed there and the surface is still there too.

I could be able to upload the map but the original java map is 40GB and the converted one is 7GB (that's a huge difference btw ?) so if you want it just ask me I will upload it on my drive.

**Comment by dadodasyra** [comment]
Just to remove an issue factor I tried directly in vanilla bedrock, it's exactly the same

**Comment by FormallyMyles** [comment]
If you're able to send a region file (.mca) impacted by this to either attach or send it to `chunker-public@hivemc.com` with relevant co-ordinates of the missing chunk(s). In the case you don't know how to do this, just move forward to the impacted chunks and look in the F3 under Chunk for the mca file name then look in region/r.x.x.mca

**Comment by dadodasyra** [comment]
> If you're able to send a region file (.mca) impacted by this to either attach or send it to `chunker-public@hivemc.com` with relevant co-ordinates of the missing chunk(s). In the case you don't know how to do this, just move forward to the impacted chunks and look in the F3 under Chunk for the mca file name then look in region/r.x.x.mca

Here's the file corresponding to the screenshot above https://drive.histeria.fr/f/84cbb88befb44771825a/

**Comment by FormallyMyles** [comment]
> > If you're able to send a region file (.mca) impacted by this to either attach or send it to `chunker-public@hivemc.com` with relevant co-ordinates of the missing chunk(s). In the case you don't know how to do this, just move forward to the impacted chunks and look in the F3 under Chunk for the mca file name then look in region/r.x.x.mca
> 
> Here's the file corresponding to the screenshot above [drive.histeria.fr/f/84cbb88befb44771825a](https://drive.histeria.fr/f/84cbb88befb44771825a/)

Thanks, we'll get this fixed for the next patch release

**Comment by FormallyMyles** [comment]
This should be fixed in the new release :)
