### ISSUE TITLE
Error Chunker Displayed: Unable to run chunker-cli backend.

### ISSUE THREAD

**Issue by whitejaws** [HiveGamesOSS/Chunker#4]
### Chunker Version

1.0.0-main-549916a

### Input World Version

bedrock 1.21.20

### Output World Version

java 1.21

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: Unable to run chunker-cli backend.

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:
- Does Chunker show the select output version screen before showing this message or is this upon upload?
- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)

**Comment by FormallyMyles** [comment]
Closing this ticket as there was no reply, I've seen a few minor cases where your operating system doesn't unzip Chunker properly you might find that just relaunching the application fixes the issue. Otherwise if you have more info, we can investigate :)
