### ISSUE TITLE
Support for Windows ARM64

### ISSUE THREAD

**Issue by Max-RM** [HiveGamesOSS/Chunker#41]
### What feature would you like seen in Chunker?

I tried to compile Chunker App to Windows 11 ARM64, but got this error:

```
\Users\MaxRM\Downloads\GitHub\Chunker>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\MaxRM\Downloads\GitHub\Chunker\app\build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.node-gradle.node', version: '7.0.2']
> Failed to apply plugin 'com.github.node-gradle.node'.
   > A problem occurred starting process 'command 'uname''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
```

**Comment by FormallyMyles** [comment]
This seems related to the node plugin we use for gradle which I believe they're aware of and a fix is in the pipeline - https://github.com/node-gradle/gradle-node-plugin/issues/315

To work around this you could need to build the `cli` folder, then install/use your own node/npm to build the `app` folder

**Comment by FormallyMyles** [comment]
This should be fixed in the latest version 1.1.3 if you wanted to try rebuilding, let us know if it's not :)

**Comment by Max-RM** [comment]
> Это должно быть исправлено в последней версии 1.1.3. Если вы хотите попробовать пересобрать, дайте нам знать, если это не так :)

Ok I will try again.

**Comment by Max-RM** [comment]
> This should be fixed in the latest version 1.1.3 if you wanted to try rebuilding, let us know if it's not :)

Hi. Now I got this error:

[Chunker.txt](https://github.com/user-attachments/files/17259926/Chunker.txt)

**Comment by FormallyMyles** [comment]
> > This should be fixed in the latest version 1.1.3 if you wanted to try rebuilding, let us know if it's not :)
> 
> Hi. Now I got this error:
> 
> [Chunker.txt](https://github.com/user-attachments/files/17259926/Chunker.txt)

Have you tried clearing the directory the log specifies `C:\\Users\\MaxRM\\Downloads\\GitHub\\Chunker\\app\\node_modules`?

**Comment by Max-RM** [comment]
> > > This should be fixed in the latest version 1.1.3 if you wanted to try rebuilding, let us know if it's not :)
> > 
> > 
> > Hi. Now I got this error:
> > [Chunker.txt](https://github.com/user-attachments/files/17259926/Chunker.txt)
> 
> Have you tried clearing the directory the log specifies `C:\\Users\\MaxRM\\Downloads\\GitHub\\Chunker\\app\\node_modules`?

Not yet

**Comment by Max-RM** [comment]
> Have you tried clearing the directory the log specifies

[Chunker000.txt](https://github.com/user-attachments/files/17260135/Chunker000.txt)
Now this error

**Comment by Max-RM** [comment]
> That error seems to indicate that it ran out of memory while building

No. I have 7 GB of free space. Should be enought

**Comment by Max-RM** [comment]
> ran out of memory

Or you meant RAM, not ROM?

**Comment by Max-RM** [comment]
> That error seems to indicate that it ran out of memory while building, you can try building without tests `-x test`

Problem was in fact that after previous attemps JAVA still was in process list and take about 2 GB of RAM. After close those process I got new error:

[Chunker001.txt](https://github.com/user-attachments/files/17260784/Chunker001.txt)

**Comment by Max-RM** [comment]
@FormallyMyles

**Comment by FormallyMyles** [comment]
> > That error seems to indicate that it ran out of memory while building, you can try building without tests `-x test`
> 
> Problem was in fact that after previous attemps JAVA still was in process list and take about 2 GB of RAM. After close those process I got new error:
> 
> [Chunker001.txt](https://github.com/user-attachments/files/17260784/Chunker001.txt)

I would guess this might still be related to you running out of memory (RAM) since the daemon shouldn't just die, I did a quick test and this works for me on a ARM machine using 8GB of RAM. 

You may want to disable tests e.g. `gradlew build -x test` as they do consume quite a bit of memory / time.

**Comment by Max-RM** [comment]
> > > That error seems to indicate that it ran out of memory while building, you can try building without tests `-x test`
> > 
> > 
> > Problem was in fact that after previous attemps JAVA still was in process list and take about 2 GB of RAM. After close those process I got new error:
> > [Chunker001.txt](https://github.com/user-attachments/files/17260784/Chunker001.txt)
> 
> I would guess this might still be related to you running out of memory (RAM) since the daemon shouldn't just die, I did a quick test and this works for me on a ARM machine using 8GB of RAM.
> 
> You may want to disable tests e.g. `gradlew build -x test` as they do consume quite a bit of memory / time.

This time I watched in the task manager and there was no RAM overflow. The maximum was 80%. but I'll try again with the 'gradle build -x test`

**Comment by Max-RM** [comment]
> > > That error seems to indicate that it ran out of memory while building, you can try building without tests `-x test`
> > 
> > 
> > Problem was in fact that after previous attemps JAVA still was in process list and take about 2 GB of RAM. After close those process I got new error:
> > [Chunker001.txt](https://github.com/user-attachments/files/17260784/Chunker001.txt)
> 
> I would guess this might still be related to you running out of memory (RAM) since the daemon shouldn't just die, I did a quick test and this works for me on a ARM machine using 8GB of RAM.
> 
> You may want to disable tests e.g. `gradlew build -x test` as they do consume quite a bit of memory / time.

Still not enought memory but this time It took longer.
[Chunker002.txt](https://github.com/user-attachments/files/17261450/Chunker002.txt)

But I have another idea.

Can you just send here your build?

**Comment by Max-RM** [comment]
> I did a quick test and this works for me

Can you send your compiled build here?
I just want to run it on my device.

**Comment by Max-RM** [comment]
> > > I did a quick test and this works for me
> > 
> > 
> > Can you send your compiled build here? I just want to run it on my device.
> 
> I sent you an email with a copy of it as i'm unable to upload it here, I did briefly test it and it seemed to work but obviously windows and arm64 is still a relatively new thing in the development world so your mileage might vary.

Ok. Btw Windows ARM32 will never get support?

**Comment by FormallyMyles** [comment]
> > > > I did a quick test and this works for me
> > > 
> > > 
> > > Can you send your compiled build here? I just want to run it on my device.
> > 
> > 
> > I sent you an email with a copy of it as i'm unable to upload it here, I did briefly test it and it seemed to work but obviously windows and arm64 is still a relatively new thing in the development world so your mileage might vary.
> 
> Ok. Btw Windows ARM32 will never get support?

We'll definitely have automatic builds when GitHub supports ARM64 for linux / windows, unsure on 32 though

**Comment by Max-RM** [comment]
> We'll definitely have automatic builds when GitHub supports ARM64 for linux / windows, unsure on 32 though

Ok

**Comment by Max-RM** [comment]
> > > > > I did a quick test and this works for me
> > > > 
> > > > 
> > > > Can you send your compiled build here? I just want to run it on my device.
> > > 
> > > 
> > > I sent you an email with a copy of it as i'm unable to upload it here, I did briefly test it and it seemed to work but obviously windows and arm64 is still a relatively new thing in the development world so your mileage might vary.
> > 
> > 
> > Ok. Btw Windows ARM32 will never get support?
> 
> We'll definitely have automatic builds when GitHub supports ARM64 for linux / windows, unsure on 32 though

I will ask my friend to try compile it

**Comment by Max-RM** [comment]
> > > > > I did a quick test and this works for me
> > > > 
> > > > 
> > > > Can you send your compiled build here? I just want to run it on my device.
> > > 
> > > 
> > > I sent you an email with a copy of it as i'm unable to upload it here, I did briefly test it and it seemed to work but obviously windows and arm64 is still a relatively new thing in the development world so your mileage might vary.
> > 
> > 
> > Ok. Btw Windows ARM32 will never get support?
> 
> We'll definitely have automatic builds when GitHub supports ARM64 for linux / windows, unsure on 32 though
<img width="1200" alt="image_2024-10-07_23-34-57" src="https://github.com/user-attachments/assets/10ebbaa4-2aea-4e77-be7e-091b7df89d76">
It works

**Comment by Max-RM** [comment]
> I would guess this might still be related to you running out of memory (RAM) since the daemon shouldn't just die, I did a quick test and this works for me on a ARM machine using 8GB of RAM.
I think I understand why we have same space of RAM, but it failed on my side.
I have disabled "SWAP FILE" because of lack of ROM.

I will enable it again and try to compile again.

**Comment by Max-RM** [comment]
> unsure on 32 though

What about make something like custom auto script to compile it?
Because I think GitHub will never support ARM32 platforms.

**Comment by FormallyMyles** [comment]
> > unsure on 32 though
> 
> What about make something like custom auto script to compile it? Because I think GitHub will never support ARM32 platforms.

One of those things that we don't have plans for official support unless there's great demand for it and considering ARM64 seems a lot more popular (at least from my perspective).

**Comment by Max-RM** [comment]
> > > unsure on 32 though
> > 
> > 
> > What about make something like custom auto script to compile it? Because I think GitHub will never support ARM32 platforms.
> 
> One of those things that we don't have plans for official support unless there's great demand for it and considering ARM64 seems a lot more popular (at least from my perspective).

ок. Btw here is latest Chunker app 1.3.0 (exe was unpacked because it will work faster if unpack it)
https://www.mediafire.com/file/9foc6yln7qesg6c/Chunker-app-1.3.0-arm64.7z/file
