### ISSUE TITLE
Desktop Version

### ISSUE THREAD

**Issue by XYCode-Kerman** [HiveGamesOSS/Chunker#44]
### What feature would you like seen in Chunker?

I would to have a desktop version. You know, because of the GFW.

![image](https://github.com/user-attachments/assets/7b483b62-d9e1-4f9d-86c5-09b72a89b86e)

**Comment by FormallyMyles** [comment]
That is exactly what the open-source version is, downloads - https://github.com/HiveGamesOSS/Chunker/releases/tag/1.1.2
