### ISSUE TITLE
Shulker boxes stored as items do not have their contents migrated

### ISSUE THREAD

**Issue by budak7273** [HiveGamesOSS/Chunker#46]
### Chunker Version

1.1.1-main-79e9191

### Input World Version

1.21.20

### Output World Version

Java 1.21.0

### Platform / Operating System

Windows 10

### Issue Description

Shulker boxes stored as items contained in other inventories (ex. in chests) become empty upon migration.

I know I am submitting this one patch version behind, but seeing as [1.1.2](https://github.com/HiveGamesOSS/Chunker/releases/tag/1.1.2)'s patch notes don't mention anything about this, I doubt it's fixed.

I reviewed your ["Out of Scope Changes / Features"](https://github.com/HiveGamesOSS/Chunker/blob/06917aa30e3e643c14770ed9dc5ad83e5e0ad5a2/CONTRIBUTING.md#out-of-scope-changes--features) section, and shulker box contents are not entities nor structure data, so I submitted this as an (in-scope) bug and not a feature request.

Note: Shulker boxes placed as blocks in the world DO have their contents migrated correctly.

To reproduce:

In bedrock, place a shulker box and put any item inside. Collect the shulker box and place it inside a chest. Convert the world to java. The box will be empty.

**Comment by FormallyMyles** [comment]
That's definitely a bug, we'll take a look into this and get it fixed.

**Comment by FormallyMyles** [comment]
This should be fixed in our latest release 1.1.3 - https://github.com/HiveGamesOSS/Chunker/releases, let us know if there's any issues :)
