### ISSUE TITLE
Error trying to convert a world

### ISSUE THREAD

**Issue by Azrian0** [HiveGamesOSS/Chunker#5]
### Chunker Version

1.0.0-main-549916a

### Input World Version

Java 1.21.1

### Output World Version

Bedrock 1.21.20

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion. 
Error identifier: bba5fcf2-21fb-4b22-86ca-252853991ed5

Heya I'm trying to convert a world.
It used to be a paper server that I got working on singleplayer and now I'm trying to convert it to bedrock for my players, but alas I am not able to..

Any idea?

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from %APPDATA%/chunker-electron/logs, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by Azrian0** [comment]
> If you're able to provide the following so we can look further into the issue:
> 
> * Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
> * The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

Sure here is my logs,  [main.log](https://github.com/user-attachments/files/16751389/main.log)

I've just emailed my world file as of 8/26/2024 at 1:22PM

**Comment by FormallyMyles** [comment]
Would you be able to confirm the amount of RAM / Processor your computer has? The logs show that it ran out of memory, it should show a different error if that happens but seems if so it crashed before that happened.

**Comment by Azrian0** [comment]
> Would you be able to confirm the amount of RAM / Processor your computer has? The logs show that it ran out of memory, it should show a different error if that happens but seems if so it crashed before that happened.

I have 16gb of RAM on my computer, should be enough?

**Comment by FormallyMyles** [comment]
We've improved the memory detection in the latest release to give a more friendly error in cases like this https://github.com/HiveGamesOSS/Chunker/releases/, if you need any other help let us know :)
