### ISSUE TITLE
slabs placements changes when converting from bedrock to java

### ISSUE THREAD

**Issue by PoyrazD12** [HiveGamesOSS/Chunker#51]
### Chunker Version

1.26.0

### Platform / Operating System

windows 11

### Issue Description

slabs placements changes when converting from bedrock to java, top slabs become down slabs and down slabs become top slabs for some reason, since I have lots of slabs in my world, this problem is making it impossible for me to convert the world properly. 
thanks for the help.

**Comment by FormallyMyles** [comment]
The issue tracker covers the new downloadable version of Chunker which you can find at https://github.com/HiveGamesOSS/Chunker/releases you may find your issue is resolved.
