### ISSUE TITLE
failed to convert world

### ISSUE THREAD

**Issue by ItsMrHexx** [HiveGamesOSS/Chunker#52]
### Chunker Version

1.1.2-main-06917aa

### Input World Version

Java 1.20.6

### Output World Version

Java 1.20.1

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
194a5e91-77dc-4d5b-96c9-cccae75c9198

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by ItsMrHexx** [comment]
I emailed a copy of both, the email is hunterostrander1@gmail.com

**Comment by FormallyMyles** [comment]
Seems to be the same issue as https://github.com/HiveGamesOSS/Chunker/issues/45, should be fixed in the next release
