### ISSUE TITLE
Error identifier: c2350c29-4192-449a-8edd-84380bf45d06

### ISSUE THREAD

**Issue by lxuxuan01** [HiveGamesOSS/Chunker#57]
### Chunker Version

1.1.2-main-06917aa

### Input World Version

Bedrock

### Output World Version

java

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error identifier: c2350c29-4192-449a-8edd-84380bf45d06

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Closing as we hadn't heard back from you, if the error still persists please provide the info above and we'd be glad to look further :)
