### ISSUE TITLE
Bring back 64bit (if possible)

### ISSUE THREAD

**Issue by timtkdb** [HiveGamesOSS/Chunker#58]
### What feature would you like seen in Chunker?

In the intial release there was a 64bit version for windows but in every release after there has on been x86.
While converting big worlds chunker uses lots of resources and it would be better if wasnt slowed down by being 32bit as to my knowlege 32bit can only use 4gb of ram.

**Comment by timtkdb** [comment]
i just checked the x64 and its 32bit? strange but still a 64bit would be nice.

**Comment by FormallyMyles** [comment]
While the electron app is technically 32-bit, it will run the backend in 64-bit mode so it will use more than 4gb of RAM if it's available / needs to. This is usually needed with much larger maps, the core limiting factor if it's not using all your RAM will likely be disk speed / CPU.
