### ISSUE TITLE
The villagers have disappeared

### ISSUE THREAD

**Issue by Ivans84qq** [HiveGamesOSS/Chunker#59]
### Chunker Version

I am using chunker.app website

### Input World Version

Java 1.20.4 (PC)

### Output World Version

Bedrock 1.20.51.01 (android)

### Platform / Operating System

Windows 10 / android 

### Issue Description

After the transfer of the world from java to bedrock, all the villagers of the village disappeared. At the same time, I tried to transfer the world to Java 1.21.1 (on my PC) and there was no such error. 

P.S I'm sorry that I don't know the version of chunker. Nowhere does it say whose project the chunker.app website is, so I decided to write here. if anything, I moved the worlds two days ago.

**Comment by FormallyMyles** [comment]
This issue tracker covers the downloadable Chunker at https://github.com/HiveGamesOSS/Chunker/releases

Additionally Chunker doesn't support entity conversion which is why villagers will disappear.
