### ISSUE TITLE
Java to Bedrock Conversion Error

### ISSUE THREAD

**Issue by V1Z0Virus** [HiveGamesOSS/Chunker#63]
### Chunker Version

1.1.3-main-ac2a40f

### Input World Version

Java 1.21.1

### Output World Version

Bedrock 1.21.0

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
Error identifier: a7c9739a-10b2-4be2-8009-2f73113c464f

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Thanks for sending this, seems to be related to the NBT limits we have in place, we'll increase the limits for the next release which will hopefully allow you to try converting the map.
