### ISSUE TITLE
World Conversion Issue

### ISSUE THREAD

**Issue by WhateverLime408** [HiveGamesOSS/Chunker#68]
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.20.30

### Output World Version

Java 1.20.4

### Platform / Operating System

win32-x64-10.0.22635

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
![image](https://github.com/user-attachments/assets/878c8399-5318-4219-b786-47a244c2581b)

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
We didn't hear back from you but if i were to guess this might be the same issue as https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.
