### ISSUE TITLE
World Conversion Issue from Bedrock to Java

### ISSUE THREAD

**Issue by stewblez** [HiveGamesOSS/Chunker#81]
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.1

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

[main.log](https://github.com/user-attachments/files/17397199/main.log)

**Comment by FormallyMyles** [comment]
This seems like a duplicate of https://github.com/HiveGamesOSS/Chunker/issues/71, we'll update that issue when a fix is released.
