### ISSUE TITLE
Error on my world?

### ISSUE THREAD

**Issue by Melvin076** [HiveGamesOSS/Chunker#9]
### Chunker Version

1.0.0-main-549916a

### Input World Version

Java 1.16.4

### Output World Version

N/A

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

cf408059-803d-4ab6-b4b3-f2f02f2cf189

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by Melvin076** [comment]
I have just send a email to you, with the logs and a url for the map

**Comment by Melvin076** [comment]
but what is this folder being used for?

**Comment by FormallyMyles** [comment]
This should be now fixed in the latest release https://github.com/HiveGamesOSS/Chunker/releases/, if not let us know and we can look into it further.
