### ISSUE TITLE
I cant convert my minecraft bedrock world to java

### ISSUE THREAD

**Issue by kay123** [HiveGamesOSS/Chunker#93]
### Chunker Version

1.2.0-main-4ae23ae

### Input World Version

Bedrock 1.21.30

### Output World Version

Java 1.21.1

### Platform / Operating System

win32-x64-10.0.22631

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment]
If you want to try with the latest release 1.3.0 - https://github.com/HiveGamesOSS/Chunker/releases and let us know if it still occurs.
