### ISSUE TITLE
Error Chunker

### ISSUE THREAD

**Issue by FellipeSilveira07** [HiveGamesOSS/Chunker#97]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Java 1.21.1

### Output World Version

Bedrock 1.21.30

### Platform / Operating System

win32-x64-10.0.26100

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.
2434a39d-767e-48db-b539-9c26d88d3dda this is the error indentifier

**Comment by FormallyMyles** [comment]
If you're able to provide the following so we can look further into the issue:

- Can you send a copy of your main.log from `%APPDATA%/chunker-electron/logs`, you'll want to put that path into Explorer / Run dialog (Windows Key + R)
- The world if possible or a world that produces the same error, you can also email it to `chunker-public@hivemc.com`.

**Comment by FormallyMyles** [comment]
Going to close this issue as I haven't heard back from you, if you're still running into this please provide the above and we can look further :)
