### ISSUE TITLE
Chest/Banners fail conversion when missing the correct backing block

### ISSUE THREAD

**Issue by Felipe34445** [HiveGamesOSS/Chunker#99]
### Chunker Version

1.3.0-main-2cdf4aa

### Input World Version

Bedrock 1.21.30

### Output World Version

Bedrock 1.21.30

### Platform / Operating System

win32-x64-10.0.19045

### Issue Description

Error Chunker Displayed: A fatal error occurred during conversion.

**Comment by FormallyMyles** [comment]
This seems related to bad block entity data in the world leading to conversion failure, we'll get this improved for the next release so it at least continues the conversion.

**Comment by FormallyMyles** [comment]
This should be fixed in the latest release - https://github.com/HiveGamesOSS/Chunker/releases :)
